* trunk/apps/utilities/livecdtools/usbdump 	  Usbdump fixes. 	* trunk/apps/utilities/livecdtools/install-finish 	  Fix GRUB Menu Title. 	* trunk/apps/belenix_constructor/src/build_dist.lib 	* trunk/apps/belenix_constructor/src/build_dist.bash 	  Add calculation of IMAGE_SIZE for updated Caiman installer. 	  Move GNOME pre-configuration to before boot archive creation. 	* trunk/apps/belenix_constructor/src/bootcd_skel/etc/modules_relocate.list 	  Add more drivers to be relocated. 	* trunk/apps/belenix_constructor/test_data/pkgs.txt 	  Bump Nvidia and OSS to newer versions. Nvidia driver is now 7.5MB UGH. 	* trunk/misc/brand/zonesupport/bzfscreatezone 	* trunk/misc/brand/zonesupport/bzfscfg.conf 	* trunk/misc/brand/zonesupport/prototype 	  More zone creation fixes. 	  New config file to indicate snapshot to be used. 	* trunk/misc/flashplayer/geturl 	* trunk/misc/flashplayer/prototype 	* trunk/misc/flashplayer/Makefile 	* trunk/misc/flashplayer/pkginfo 	  Remaining bits needed to allow us to build a Flashplayer package. 	* trunk/spec_files/SFEuwimap.spec 	* trunk/spec_files/patches/imap-01.diff 	  Add IMAP package used by PHP5 for eg. 	* trunk/spec_files/firefox3/patches/firefox3-11-getting-started-bookmark.diff 	  Modify default homepage for BeleniX. 	* trunk/spec_files/SUNWsolnm.spec 	  Bump release information.

diff --git a/misc/brand/zonesupport/bzfscreatezone b/misc/brand/zonesupport/bzfscreatezone
--- a/misc/brand/zonesupport/bzfscreatezone
+++ b/misc/brand/zonesupport/bzfscreatezone
@@ -31,8 +31,30 @@ ZONE_SUBPROC_USAGE=253
 ZONE_SUBPROC_NOTCOMPLETE=254
 ZONE_SUBPROC_FATAL=255
 
-#SYS_RPOOL=rpool/ROOT/preview2
-SYS_RPOOL=`nawk '{ if (match($2, "^\/$") > 0) print $1 }' /etc/mnttab`
+ZONES_SNAP=""
+
+if [ ! -f /etc/bzfscfg.conf ]
+then
+	echo "Config file /etc/bzfscfg.conf not found. Aborting!"
+	exit 1
+fi
+
+. /etc/bzfscfg.conf
+if [ -n "$ZONES_SNAP" ]
+then
+	zfs list $ZONES_SNAP 2>&1 > /dev/null
+	if [ $? -ne 0 ]
+	then
+		echo "Specified pool $ZONES_SNAP not found."
+		echo "Defaulting to root pool"
+		ZONES_SNAP=""
+	fi
+fi
+
+if [ "$ZONES_SNAP" = "" ]
+then
+	ZONES_SNAP=`nawk '{ if (match($2, "^\/$") > 0) print $1 }' /etc/mnttab`
+fi
 
 f_img=$(gettext "failed to create image")
 
@@ -100,8 +122,8 @@ mkdir -p $zonepath/root
 printf "$m_done\n"
 
 printf "$m_core\n"
-zfs clone ${SYS_RPOOL}@install ${SYS_RPOOL}/${zonename} 
-zfs set mountpoint=$zoneroot ${SYS_RPOOL}/${zonename}
+zfs clone ${ZONES_SNAP} ${ZONES_DATASET}/${zonename} 
+zfs set mountpoint=$zoneroot ${ZONES_DATASET}/${zonename}
 
 printf "$m_smf"
 rm -f $zoneroot/var/svc/profile/name_service.xml
@@ -120,6 +142,7 @@ chmod 0600 $repfile
 chown root:sys $repfile
 
 rm -f $zoneroot/var/svc/manifest/system/sysevent.xml
+rm -f $zoneroot/var/svc/manifest/system/device/devices-fc-fabric.xml
 echo "$zonename" > $zoneroot/etc/nodename
 
 printf "$m_done\n"
